apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  postgres-user: cG9zdGdyZXM= # postgres
  postgres-password: cG9zdGdyZXM= # postgres
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRiLXNlcnZpY2U6NTQzMi9uZ29fZGI= # postgresql://postgres:postgres@db-service:5432/ngo_db
  secret-key: ZjMzYmM1ZTcxYzQ4N2E0ZTkwNjZjYmRhZTU5ZTZkODA3YmUzYzJlMTJlZjRmZjRlNGNlYzkzYTc4YTkxNzk2ZQ== # 64-hex flask SECRET_KEY (regenerate per environment)
